apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubermatic
secretGenerator:
- name: kubermatic-values
  files:
  - values.yaml=../../kubermatic/values.yaml
  options:
    disableNameSuffixHash: true
