apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: kubermatic
spec:
  chart:
    spec:
      chart: charts/monitoring/kube-state-metrics
      sourceRef:
        kind: GitRepository
        name: kubermatic-git
        namespace: kubermatic
  interval: 5m
  releaseName: kube-state-metrics
  storageNamespace: monitoring
  targetNamespace: monitoring
  valuesFrom:
    - kind: Secret
      name: kubermatic-values
      valuesKey: values.yaml
