apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: kubermatic
spec:
  chart:
    spec:
      chart: charts/monitoring/prometheus
      sourceRef:
        kind: GitRepository
        name: kubermatic-git
        namespace: kubermatic
  interval: 5m
  releaseName: prometheus
  storageNamespace: monitoring
  targetNamespace: monitoring
  valuesFrom:
    - kind: Secret
      name: kubermatic-values
      valuesKey: values.yaml
