apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: iap
  namespace: kubermatic
spec:
  chart:
    spec:
      chart: charts/iap
      sourceRef:
        kind: GitRepository
        name: kubermatic-git
        namespace: kubermatic
  interval: 5m
  releaseName: iap
  storageNamespace: iap
  targetNamespace: iap
  valuesFrom:
    - kind: Secret
      name: kubermatic-values
      valuesKey: values.yaml
