apiVersion: kubermatic.k8c.io/v1
kind: Preset
metadata:
    name: kkp
    namespace: kubermatic
spec:
    azure:
        tenantId: ENC[AES256_GCM,data:f01RraP8V1fP+CEgpXEQ9lqW+YF/5M1w0JeoEko4vzQH0ZmM,iv:xv5dw/uLRKRR9FhYrQO52RBF6soUCGBC+VGfmSCJYvo=,tag:AvrV99ngqzj6i4o8IOH5gA==,type:str]
        subscriptionId: ENC[AES256_GCM,data:6yoVRuD1iVjCVymiE3y+zfRFsdpt0TCdJz3iR0fQAqqN2n9j,iv:N+k1mdWF/NWNW7Mu6rmCFVAp7qY7Mkklvnymgyg5jnk=,tag:EwTi81PrlBMNH6trL5VOig==,type:str]
        clientId: ENC[AES256_GCM,data:/Dl+QG9wci9zbjqXPf4ZrQpHml88mQmBBWWPf967XPVcTA1H,iv:fwMJz+vMofOx8ZWgExvwRzH4Mkj5pEI0W0ugNcGPrWs=,tag:syhplR4L8z+/dkkHkfaDgw==,type:str]
        clientSecret: ENC[AES256_GCM,data:kQClhiusQ5u6+O9Q+BL4RAMcKtm1GUQjyNnKmjhGkzwF4Q==,iv:CyHy97v1oJSmr2NUt5/WTyRPnInReqdaC1txs5++S9E=,tag:uST/T2/zQlm8KWuQ7J0ZMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17d68hneuxnfe7avsu608ea6wv9v9gvr93vlxtvk8zd25s3kan46q0n4zvm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TzVMcXhIV0EzWWZYSVdL
            dnl2UDFOV2FVNk9KdDNqMVZlRzY4SDhOQWdBClFSVkhWWDJyRzBnOUNPd0M3bTlR
            N1o5d3l4anU4MFlZU1gvUXRwUEZ3d0UKLS0tIEJQa28ybFZMa2ttN3JPMGZaV1Nk
            Z3o0eWtyZWFiSzh5TG1PNjU5ZWtjeEkKUPRoQAbYODA0afTxCQshGShaJ4zh+qAg
            gST1bMbOzs3Lu5m+d4ZM/ptBqaaiEe2ViFD/7UoTemtsz9TVee2ECA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-21T13:13:31Z"
    mac: ENC[AES256_GCM,data:sdX9rommno5Vn1pNvuudypFXB8wsCB2OKJEKIXAChGTLMqSTwvPxSr2MwlnJAxvqd48lwG+FSwMCYTHZTIeOIjr6rvHhQYd8LqnY3zkDPrDLlVgc/o+pYSbLWsCveZP4X4rjqQginLWUYELQxboU3jyShQS5f1e7ThA3P3S42eM=,iv:6LLnsQL60b1sLgQuLnMoPyOaU+2PFgsQH93OYi+Mfhs=,tag:iuBYl4EqLebkUOrmRdsgpw==,type:str]
    pgp: []
    encrypted_regex: (accessKeyID|secretAccessKey|username|password|tenantId|subscriptionId|clientId|clientSecret|serviceAccount)
    version: 3.7.1
