dex:
    ingress:
        host: azure-test.kkp.io
    certIssuer:
        name: letsencrypt-prod
        kind: ClusterIssuer
    env:
        - name: KUBERNETES_POD_NAMESPACE
          value: oauth
    staticPasswords:
        - email: vijay
          hash: ENC[AES256_GCM,data:jwAGeILq76p1HgdFgHeVnOg/pNGEjwwvcrrZXldzIO/+v/lix2D3sFU0DOHBh19uunKMOFh5zOyvhzc/,iv:ATcd64lIPAps/KqoQrdXSUMHHOpk6hmogZbhXUsGCOQ=,tag:DPeUzZccgJfcAmLO/GLE+A==,type:str]
          username: vijay
          userID: fcfa2d34-62a0-44ed-869e-ab66e3691da5
    clients:
        - id: kubermatic
          name: Kubermatic
          secret: ENC[AES256_GCM,data:GAuGNLNIPFNaXCrdgY1dtxRoKJfNVeEjNg6feSiyCwI=,iv:m9EZrdqj09xtJILGvOjHOTgl8pkaDZvw5slKWs/SgdM=,tag:QJU/oKuGLgwki25V/lWdng==,type:str]
          RedirectURIs:
            - https://azure-test.kkp.io
            - https://azure-test.kkp.io/projects
        - id: kubermaticIssuer
          name: Kubermatic OIDC Issuer
          secret: ENC[AES256_GCM,data:5Fqz0M1e39D5gIM1PRQ2Cw==,iv:2JGn9M1d0D8350G+ozNY50KWvhFXe7hXoGs7NXMAgIg=,tag:tCeFekdp4iaLX8ZxCMcDqg==,type:str]
          RedirectURIs:
            - https://azure-test.kkp.io/api/v1/kubeconfig
        - id: prometheus
          name: Prometheus
          secret: ENC[AES256_GCM,data:LY1kVjogZaxB2FwTo+Kfbg==,iv:WJo8ESFDi8sgAHRDxDGhS5JR7OrxjQBcAtpEG12Leh0=,tag:2YHt+ZzpRMhNk+3A2Lzbfg==,type:str]
          RedirectURIs:
            - https://prometheus.azure-test.kkp.io/oauth/callback
        - id: alertmanager
          name: Alertmanager
          secret: ENC[AES256_GCM,data:pv67byLvoFRmvFg1+gqXeQ==,iv:JbJHcuvYM+To9iPoWK7E/gR/8RDnFni/pTcUbQgeeZI=,tag:y8QjBKVVFphCkdhVjjRTaw==,type:str]
          RedirectURIs:
            - https://alertmanager.azure-test.kkp.io/oauth/callback
        - id: grafana
          name: Grafana
          secret: ENC[AES256_GCM,data:YBWnwommEQZ+ATef7Yw7Nw==,iv:UPXKcl1UmyH+hhsj8f/YNelwR94UnEYJqLwmHlEPT3A=,tag:GTcQFDku05mG5rFNcLk3EA==,type:str]
          RedirectURIs:
            - https://grafana.azure-test.kkp.io/oauth/callback
        - id: karma
          name: Karma
          secret: ENC[AES256_GCM,data:f7SylHRiZpioDHhlnNEF1A==,iv:tbw1DrOqKk3AkJP1yK4hufg919SOkG7Sflu6RKw3zB4=,tag:FsaWYDtpyKxoWT7q7y3mmQ==,type:str]
          RedirectURIs:
            - https://karma.azure-test.kkp.io/oauth/callback
alertmanager:
    host: alertmanager.azure-test.kkp.io
grafana:
    user: admin
    password: ENC[AES256_GCM,data:hWz2hZBFOwS1vqpnGm2vsQ==,iv:5Sn01WAx43yxxJ/rp1VF3nGwnaAPhnmFqwcBLNvgzDE=,tag:UilvhgrtlrX+B1ksEsanPg==,type:str]
    provisioning:
        configuration:
            auto_assign_org_role: Editor
            disable_login_form: false
            root_url: https://grafana.azure-test.kkp.io
        datasources:
            lokiServices:
                - loki
prometheus:
    host: prometheus.azure-test.kkp.io
    storageSize: 125Gi
    tsdb:
        retentionTime: 7d
    ruleFiles:
        - /etc/prometheus/rules/general-*.yaml
        - /etc/prometheus/rules/kubermatic-*.yaml
        - /etc/prometheus/rules/managed-*.yaml
iap:
    oidc_issuer_url: https://azure-test.kkp.io/dex
    deployments:
        prometheus:
            name: prometheus
            ingress:
                host: prometheus.azure-test.kkp.io
            upstream_service: prometheus.monitoring.svc.cluster.local
            upstream_port: 9090
            client_id: prometheus
            client_secret: ENC[AES256_GCM,data:Ihx204hpVjKnKxof1xZjew==,iv:PWb7CQgHVH5D0BRO3vvNOFbsWRHmI29SB+Sm10i4Lzo=,tag:Q9oXFk3d80P6hq3Q5h5YWA==,type:str]
            encryption_key: ENC[AES256_GCM,data:lBwzNyacz78xsx1wyENEwk7eRVzsGQnm55MoTRG0sOA=,iv:/nEAF+FQ/R/I79rXQ2XZITjJZuNgMDayA2ykTSQ9GL0=,tag:tzSAtaogoT/xhtZC+tkXzA==,type:str]
            config:
                scope: groups openid email
                email_domains:
                    - kubermatic.com
                pass_user_headers: true
                skip_auth_regex:
                    - /-/health
        alertmanager:
            name: alertmanager
            ingress:
                host: alertmanager.azure-test.kkp.io
            upstream_service: alertmanager.monitoring.svc.cluster.local
            upstream_port: 9093
            client_id: alertmanager
            client_secret: ENC[AES256_GCM,data:xBRcYX7jpD1bPV/909uJkw==,iv:zSF7ix6+JI77KdH/uBg7qIyKY+/IGFcyCtTQYOYTNM4=,tag:oFYRptzUlRuGNlqTs3+i6w==,type:str]
            encryption_key: ENC[AES256_GCM,data:gMEPZ43+QWkly9gJPpq8wQ1GHpf9tGpfw//j5Jv+B7I=,iv:6ZLZPwBoZY6q7mFyDCFOdOSR6E6uElSxmb0Gj7HH6Jk=,tag:3sS+7cygTKFZSOAp6v+v8A==,type:str]
            config:
                scope: groups openid email
                email_domains:
                    - kubermatic.com
                pass_user_headers: true
                skip_auth_regex:
                    - /-/health
        grafana:
            name: grafana
            ingress:
                host: grafana.azure-test.kkp.io
            upstream_service: grafana.monitoring.svc.cluster.local
            upstream_port: 3000
            client_id: grafana
            client_secret: ENC[AES256_GCM,data:E4TMaXKAy+Sp6BfZfR8PUg==,iv:MbkMUaGurZCM0gMRraCU+RO6Y+XqxUz6/Bs9tiV7Gwc=,tag:6LnYUBAqI87fytUvWhHWFA==,type:str]
            encryption_key: ENC[AES256_GCM,data:kHSP/A33o4x+tpt7dgXDw/wmb0dGpcW20oRQgmKh4lY=,iv:Jk39YGKR6IT0jjUjt0UmgRsxlyhrlHNkMsMWNJA1BSo=,tag:3WigHoZ20SuAzm7JoYkeaA==,type:str]
            config:
                scope: groups openid email
                email_domains:
                    - kubermatic.com
                pass_user_headers: true
                skip_auth_regex:
                    - /api/health
        karma:
            name: karma
            ingress:
                host: karma.azure-test.kkp.io
            upstream_service: karma.monitoring.svc.cluster.local
            upstream_port: 8080
            client_id: karma
            client_secret: ENC[AES256_GCM,data:Zg8oHJzDEMpu2jcVCySqnQ==,iv:aV0++F3FseCq5UU31vM3PJ8SVuaPAZ0+XaGN6hyLiRA=,tag:zcNx2tFqoiIvXkvRnG3nhg==,type:str]
            encryption_key: ENC[AES256_GCM,data:ZMv3UE2nBVT90nAkhw3wInCYR/i1a9br1foSVqk+sv8=,iv:E2FhzMbFCISAT4xNPe+bkZiyuJB0kOLToUjSL9JIziY=,tag:ZLxYreMLzDHGvJmki2LJgg==,type:str]
            config:
                scope: groups openid email
                email_domains:
                    - kubermatic.com
                pass_user_headers: true
telemetry:
    # uuid is the unique identifier of the client where the agent is running.
    # This field is required and will print an error message when that entry is missing.
    uuid: d215b77e-edb2-43c1-be2d-7d45d3b2772c
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ty4mfhmw0gr844zy3pay7czqv786sgyj30edelhaynmuxu78spzssnft40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYnBEL085OFBHMXUyYjBL
            OGQ5QUhPL21jU2dlS0g3NTBlQkdLTUkzOVhNCnd6NUZteWFIaTFJeStEeno0UFdj
            cVdMWndEVE1aZlJSRCtjd3A2azNhU2MKLS0tIDd4NG02U0pSY3paTjUzMWN1M1VC
            bUhaeWdBVHc1NUl6dU1MMDZYYTNtSmMKl5a0fTJlgEfnhlpWt4hTP2VyfqA667pQ
            o+kQjgQGuCpibpTx5QNbLpTmw0nO5OJADEj0JF2Hd+1YWMfkETrLEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-15T11:34:06Z"
    mac: ENC[AES256_GCM,data:cQfHw4nYJru+ihN0hFkArVXibx2tfXTXHB4Wzu9jY6MwJWO7MIP1PUZqGroB6FsOTsfRZ1HiHO0JiaomDUgNbgRmoGfBCF+RqCipEBFNzXKSNCK7kr3uWXFU61LcKlH0YVraqCN51Gb+/mA6PJ5ruBbvgZrHjPNLltvuGSBkGng=,iv:ATCY+zzF04cynRGbqOlGVNN5pww51Tkb0LSFDM7xNyU=,tag:tPMsUv7nWql7uHA0bQi2Tw==,type:str]
    pgp: []
    encrypted_regex: (hash|secret|password|encryption_key|accessKey)
    version: 3.7.1
