apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
versions:
    kubernetes: v1.23.5
cloudProvider:
    azure: {}
    # External (CCM/CSI migration) will be supported from next release (>1.3.0) of KubeOne
    external: false
    cloudConfig: ENC[AES256_GCM,data:QT4QMN8PQelu+nI2A2PcNEYaYgA+R4vreAs8v+Lecumuy1orVvPVyA4bFr7iC/O3yfI6uNoI2ehPWCsDdTQ6ED0dF/E69v1Mpbzl4s3V9yGwWVdi/3tdXyW95NyQpQLAbLBILjGFnqiEBwYehouswaHND0Nl61RpuLVFHLo90cN6HwzgGXa4+4nCtVKvRytoMuTu3fxWt5SWRw4o2bjKFn0NnneiLZppAuVWJKp8ZFeR7tVxrdbK+IOGyV81NjU1gZKbvUlw28Oh4CB7oJ7Ve5cGYVgxnXb4Vf+rqBMO9I/WsNZ+1wNpy3mD0txAtuaVAEwTJUab5Ow1gpBBphXPJlmmK7YBqRXEorx4/RkVltd1tAOmNeI6XlULRUdFDVJXBw2RdQXaVPslzvX6SCXaSRbrCbZgo+jMMWBuuUZKDicIPJMweGQCiox1LenMsjJumgiNcwyqZZA3gaBOc6N27AZf0FIanDGInqdoxATbDlkCa89cDEX9m0121mhQSJsEUG8sOlh2/30iWwXNQObxNxkHc8Av4pXRIblNRzpEcxteCx76Q1IaGiZuP1cXXs1eD1n06HkslWsqsOlunLOY4KnT9+F3vp5ChGT7/5p9FOCjK6xVCQBf6cBDG7ccai4ZL2LhkEoC4PwNQ/WYaj3wimHI+w999eqH77gaqrznOOeIjCHIt1cpNsIHQJISog9wU3Fc3NehCZZu8FblN2DvKHuTvMiuOBlsjC3XEVDtsiHGFi1liX1CLDRPVQ==,iv:z1sQHQr+Hs/YelaiixHa8huQtg8L7GmGFkOqPBkcQp8=,tag:y2/rENr5quM2+BLVdeCQmA==,type:str]
containerRuntime:
    containerd: {}
addons:
    enable: true
    path: ./addons
    addons:
        - name: cluster-autoscaler
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ty4mfhmw0gr844zy3pay7czqv786sgyj30edelhaynmuxu78spzssnft40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNFQ2REVFY1V5WitNOWJG
            d3p1Z1V6UlJLTUhDL3Q3aFdCdU9jajlPNnpnClE0ZUp0WmowcGVvamlxVFBUWWRz
            Wk03ZlcyOXNXSXAyNFpPcXU5TW1XcWcKLS0tIFBoUEZVbmtRWEdVNHhlMTBGYmJ0
            WTY2NXFVaEFFVFBDSXJqbi91NUlrRFEKy0bDYn1EDdMpySEdISM+To5CVRAQQhEd
            lnvcGiim5y1niYpAr6MdU91DtipjuJ9PgKMc/6qbxoPHBOhklbrPrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-15T11:34:06Z"
    mac: ENC[AES256_GCM,data:i+QC77rk60ow5iiHBKu60l9a9Kpq9BbiYhkmD5SvbuEaKdaOOUnZWmLkrmbXTJt/1HAlDHTMlITYdlxMkFIQjUKqFgcFfpr7pBEWyHXRE+xQGI9MUYl0AX2OZJAQUBZd4hWeeSUfh/PN7T2HVaqqnN+EZQvPN6+0ftRPLBq/e4s=,iv:idOrzsYCa2tj+cHmgo+XEFATEnBTCQMh+E1rbk++fjs=,tag:cEBRhcRbQLnCpKmQ+ZEegQ==,type:str]
    pgp: []
    encrypted_regex: (cloudConfig)
    version: 3.7.1
