apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-issuer
  namespace: kubermatic
spec:
  interval: 2m0s
  path: applications/cert-manager-issuer
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
