apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubermatic-presets
  namespace: kubermatic
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 2m0s
  path: applications/kubermatic-presets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
