apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubermatic-project
  namespace: kubermatic
spec:
  interval: 2m0s
  path: applications/kubermatic-project
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
