apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubermatic-settings
  namespace: kubermatic
spec:
  interval: 2m0s
  path: applications/kubermatic-settings
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
