apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: kubermatic
spec:
  chart:
    spec:
      chart: charts/logging/promtail
      sourceRef:
        kind: GitRepository
        name: kubermatic-git
        namespace: kubermatic
  interval: 5m
  releaseName: promtail
  storageNamespace: logging
  targetNamespace: logging
  valuesFrom:
    - kind: Secret
      name: kubermatic-values
      valuesKey: values.yaml
