apiVersion: kubermatic.k8c.io/v1
kind: KubermaticSetting
metadata:
  name: globalsettings
spec:
  cleanupOptions:
    enabled: true
    enforced: false
  customLinks:
    - icon: ""
      label: API
      location: default
      url: https://azure-test.kkp.io/rest-api
    - icon: ""
      label: Prometheus
      location: default
      url: https://prometheus.azure-test.kkp.io
    - icon: ""
      label: Alertmanager
      location: default
      url: https://alertmanager.azure-test.kkp.io
    - icon: ""
      label: Grafana
      location: default
      url: https://grafana.azure-test.kkp.io
    - icon: ""
      label: Karma
      location: default
      url: https://karma.azure-test.kkp.io

  defaultNodeCount: 2
  displayAPIDocs: true
  displayDemoInfo: false
  displayTermsOfService: false
  enableDashboard: true
  enableExternalClusterImport: true
  enableOIDCKubeconfig: false
  machineDeploymentVMResourceQuota:
    enableGPU: false
    maxCPU: 32
    maxRAM: 128
    minCPU: 1
    minRAM: 2
  mlaAlertmanagerPrefix: ""
  mlaGrafanaPrefix: ""
  mlaOptions: {}
  opaOptions: {}
  restrictProjectCreation: false
  userProjectsLimit: 0
  